<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use yii\web\AssetBundle;
use yii\web\View;

/**
 * Main backend application asset bundle.
 */
class AppAsset extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->basePath = '@app/backend/web';
        $this->css = [
            'css/admin-all-demo.css',
            'css/site.css',
            'helpers/responsive-elements.css',
            'helpers/admin-responsive.css',
            'iconic/iconic.css',
            'elusive/elusive.css',
            'meteocons/meteocons.css',
            'spinnericon/spinnericon.css',
            'typicons/typicons.css'
        ];
        $this->js = [
            'js/admin-all-demo.js',
        ];
        $this->depends = [
            'yii\web\YiiAsset',
            'yii\bootstrap\BootstrapAsset',
            'yii\bootstrap\BootstrapPluginAsset'
        ];
        $this->jsOptions['position'] = View::POS_HEAD;
    }
}
