<?php
/**
 * Created by PhpStorm.
 * User: MyPC
 * Date: 13/03/2017
 * Time: 5:39 CH
 */

namespace app\assets;


use yii\web\AssetBundle;

class LoginAppAsset extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->basePath = '@app/web';
        $this->css = [
            'helpers/animate.css',
            'helpers/backgrounds.css',
            'helpers/boilerplate.css',
            'helpers/border-radius.css',
            'helpers/grid.css',
            'helpers/page-transitions.css',
            'helpers/spacing.css',
            'helpers/typography.css',
            'helpers/utils.css',
            'helpers/colors.css',
            'elements/badges.css',
            'elements/buttons.css',
            'elements/content-box.css',
            'elements/dashboard-box.css',
            'elements/forms.css',
            'elements/images.css',
            'elements/info-box.css',
            'elements/invoice.css',
            'elements/loading-indicators.css',
            'elements/menus.css',
            'elements/panel-box.css',
            'elements/response-messages.css',
            'elements/responsive-tables.css',
            'elements/ribbon.css',
            'elements/social-box.css',
            'elements/tables.css',
            'elements/tile-box.css',
            'elements/timeline.css',
            'icons/fontawesome/fontawesome.css',
            'icons/linecons/linecons.css',
            'icons/spinnericon/spinnericon.css',


            'widgets/accordion-ui/accordion.css',
            'widgets/calendar/calendar.css',
            'widgets/carousel/carousel.css',

            'widgets/charts/justgage/justgage.css',
            'widgets/charts/morris/morris.css',
            'widgets/charts/piegage/piegage.css',
            'widgets/charts/xcharts/xcharts.css',

            'widgets/chosen/chosen.css',
            'widgets/colorpicker/colorpicker.css',
            'widgets/datatable/datatable.css',
            'widgets/datepicker/datepicker.css',
            'widgets/datepicker-ui/datepicker.css',
            'widgets/daterangepicker/daterangepicker.css',
            'widgets/dialog/dialog.css',
            'widgets/dropdown/dropdown.css',
            'widgets/dropzone/dropzone.css',
            'widgets/file-input/fileinput.css',
            'widgets/input-switch/inputswitch.css',
            'widgets/input-switch/inputswitch-alt.css',
            'widgets/ionrangeslider/ionrangeslider.css',
            'widgets/jcrop/jcrop.css',
            'widgets/jgrowl-notifications/jgrowl.css',
            'widgets/loading-bar/loadingbar.css',
            'widgets/maps/vector-maps/vectormaps.css',
            'widgets/markdown/markdown.css',
            'widgets/modal/modal.css',
            'widgets/multi-select/multiselect.css',
            'widgets/multi-uploads/fileupload.css',
            'widgets/nestable/nestable.css',
            'widgets/noty-notifications/noty.css',
            'widgets/popover/popover.css',
            'widgets/pretty-photo/prettyphoto.css',
            'widgets/progressbar/progressbar.css',
            'widgets/range-slider/rangeslider.css',
            'widgets/slidebars/slidebars.css',
            'widgets/slider-ui/slider.css',
            'widgets/summernote-wysiwyg/summernote-wysiwyg.css',
            'widgets/tabs-ui/tabs.css',
            'widgets/theme-switcher/themeswitcher.css',
            'widgets/timepicker/timepicker.css',
            'widgets/tocify/tocify.css',
            'widgets/tooltip/tooltip.css',
            'widgets/touchspin/touchspin.css',
            'widgets/uniform/uniform.css',
            'widgets/wizard/wizard.css',
            'widgets/xeditable/xeditable.css',


            'snippets/chat.css',
            'snippets/files-box.css',
            'snippets/login-box.css',
            'snippets/notification-box.css',
            'snippets/progress-box.css',
            'snippets/todo.css',
            'snippets/user-profile.css',
            'snippets/mobile-navigation.css',


            'applications/mailbox.css',


            'themes/admin/layout.css',
            'themes/admin/color-schemes/default.css',


            'themes/components/default.css',
            'themes/components/border-radius.css',
            'helpers/responsive-elements.css',
            'helpers/admin-responsive.css',
        ];
        $this->js = [
            'js-core/jquery-core.js',
            'js-core/jquery-ui-core.js',
            'js-core/jquery-ui-widget.js',
            'js-core/jquery-ui-mouse.js',
            'js-core/jquery-ui-position.js',
            'js-core/modernizr.js',
            'js-core/jquery-cookie.js',
        ];
        $this->depends = [
            'yii\web\YiiAsset',
            'yii\bootstrap\BootstrapAsset',
        ];
        $this->jsOptions['position'] = View::POS_HEAD;
    }

}
